#!/usr/bin/env bash
# Aggregate every per-run summary.md inside results/<run-id>/ into one
# self-contained, committable report under bench/reports/<sweep>/.
#
# Output layout (all tracked in git):
#   bench/reports/<sweep>/
#   ├── report.md              ← master report
#   ├── sysinfo.txt            ← copy of sweep sysinfo
#   ├── run-all.log            ← copy of sweep log (if present)
#   └── runs/
#       └── <run-id>.md        ← copy of each results/<id>/summary.md
#
# Raw artifacts (sample.csv, runtime-*.json, metrics-*.txt, src*.log) stay
# inside results/ which is gitignored. Report links to them with a
# "(local only)" marker so reviewers know not to expect them in the repo.
#
# Usage:
#   bench/scripts/aggregate.sh <sweep-name>
#   RUNS="A1 A2 B3 C3" bench/scripts/aggregate.sh my-sweep
#
set -euo pipefail

[[ $# -ne 1 ]] && { echo "Usage: $0 <sweep-name>"; exit 1; }

SWEEP=$1
BENCH_ROOT=$(cd "$(dirname "$0")"/.. && pwd)
RESULTS=$BENCH_ROOT/results
REPORTS=$BENCH_ROOT/reports
SWEEP_RESULTS=$RESULTS/$SWEEP
SWEEP_REPORTS=$REPORTS/$SWEEP
OUT=$SWEEP_REPORTS/report.md

mkdir -p "$SWEEP_REPORTS/runs"

# ---------- collect run IDs ----------
collect_runs() {
  if [[ -n "${RUNS:-}" ]]; then
    echo "$RUNS" | tr ' ' '\n'
  else
    find "$RESULTS" -maxdepth 2 -name summary.md 2>/dev/null \
      | xargs -I{} dirname {} \
      | xargs -I{} basename {} \
      | grep -v "^$SWEEP$" \
      | sort
  fi
}

RUNS_FOUND=()
while IFS= read -r line; do
  [[ -n "$line" ]] && RUNS_FOUND+=("$line")
done < <(collect_runs)
[[ ${#RUNS_FOUND[@]} -eq 0 ]] && { echo "[aggregate] no per-run summaries found"; exit 1; }

echo "[aggregate] sweep '$SWEEP' — including ${#RUNS_FOUND[@]} runs:"
printf '  %s\n' "${RUNS_FOUND[@]}"

# ---------- copy summaries + sweep-level files into reports/ ----------
for r in "${RUNS_FOUND[@]}"; do
  src=$RESULTS/$r/summary.md
  [[ -f "$src" ]] && cp "$src" "$SWEEP_REPORTS/runs/$r.md"
done

# Prefer SWEEP-scoped sysinfo, fall back to latest top-level sysinfo
SYSINFO_SRC=""
if [[ -f "$SWEEP_RESULTS/sysinfo.txt" ]]; then
  SYSINFO_SRC=$SWEEP_RESULTS/sysinfo.txt
else
  SYSINFO_SRC=$(ls -t "$RESULTS"/sysinfo-*.txt 2>/dev/null | head -1 || echo "")
fi
[[ -n "$SYSINFO_SRC" && -f "$SYSINFO_SRC" ]] && cp "$SYSINFO_SRC" "$SWEEP_REPORTS/sysinfo.txt"

# Copy run-all log if present
[[ -f "$SWEEP_RESULTS/run-all.log" ]] && cp "$SWEEP_RESULTS/run-all.log" "$SWEEP_REPORTS/run-all.log"

# ---------- helpers ----------

# Extract the auto-generated single-line markdown row from a summary.md.
extract_row() {
  awk '
    /^## Row to paste into the master report/ {found=1; next}
    found && /^```markdown/ {inblk=1; next}
    inblk && /^```/ {exit}
    inblk {print; exit}
  ' "$1"
}

phase_of() { echo "$1" | sed -E 's/^([A-Z]).*/\1/'; }
now() { date -Iseconds 2>/dev/null || date; }
git_sha() { (cd "$BENCH_ROOT/.." && git rev-parse --short HEAD 2>/dev/null) || echo "unknown"; }

SHA=$(git_sha)
NOW=$(now)

# ---------- compose master report ----------
{
cat <<EOF
# Open-Streamer Benchmark Report — $SWEEP

> Auto-generated by \`bench/scripts/aggregate.sh\` on $NOW.
> This report and per-run summaries (\`runs/*.md\`) are committable.
> Raw artifacts (CSV, JSON snapshots, ffmpeg logs) live under
> \`bench/results/<run-id>/\` which is gitignored — keep them on the
> benchmarking host for re-analysis but do not expect to find them in git.

## 0. Metadata

| Field | Value |
| --- | --- |
| Sweep ID | \`$SWEEP\` |
| Generated | $NOW |
| Open-Streamer commit | \`$SHA\` |
| Runs included | $(IFS=,; echo "\`${RUNS_FOUND[*]}\`") |
| Tester | <TODO> |
| Goal | <TODO> |

---

## 1. Hardware & Environment

EOF

if [[ -f "$SWEEP_REPORTS/sysinfo.txt" ]]; then
  echo "Captured at sweep start (see [sysinfo.txt](sysinfo.txt)):"
  echo
  echo '```text'
  cat "$SWEEP_REPORTS/sysinfo.txt"
  echo '```'
else
  echo "_sysinfo.txt not found — run \`bench/scripts/prepare.sh sysinfo\` and inline it._"
fi

cat <<EOF

---

## 2. Open-Streamer Configuration

Per-run config snapshots are local only — see \`results/<run-id>/config.json\`
on the benchmarking host.

---

## 3. Methodology

- Warm-up: 30s discarded at start of every run.
- Steady window: 120s (2 min).
- Sample interval: 2s.
- Cooldown between runs: see \`run-all.log\`.
- Stop conditions per run:
  - **SATURATED**: CPU p95 > 90%, transcoder restart > 0, or any stream ended Degraded.
  - **FAIL**: bench script error (no summary, behavior test failed).
- Sweep aborts on first FAIL; SATURATED only skips the rest of its phase.
- Repeat for production sign-off: 3× per run, take median.

### Metric conventions

- **CPU%, RAM%, GPU%, Enc%, Dec%, VRAM(MB)** are scoped to **open-streamer
  + its direct child processes (transcoder ffmpegs)**. Bench-side load
  generators (RTMP source publishers, parent = bash) and unrelated host
  processes are excluded.
- **CPU%** is **host-relative**: \`Σ ps -o pcpu / nproc\`, so 100% means
  the entire host CPU is consumed. Matches \`top\` / Grafana node-exporter
  semantics; comparable across hosts of different core counts.
- **RAM%** is \`Σ RSS / MemTotal × 100\` (same convention).
- **GPU/Enc/Dec/VRAM** come from \`nvidia-smi pmon\` and \`--query-compute-apps\`
  filtered to the same PID set.
- **Net Rx/Tx** are interface-level (cannot be split per-process on Linux
  without root + cgroup tagging) and reflect total NIC throughput including
  source publishers.

---

## 4. Results

EOF

# Group runs by phase letter and emit one table per phase
for phase in A B C D E F H; do
  runs_in_phase=()
  for r in "${RUNS_FOUND[@]}"; do
    [[ "$(phase_of "$r")" == "$phase" ]] && runs_in_phase+=("$r")
  done
  [[ ${#runs_in_phase[@]} -eq 0 ]] && continue

  case $phase in
    A) phase_title="Phase A — Passthrough" ;;
    B) phase_title="Phase B — Legacy ABR transcoding (NVENC, 1 ffmpeg/rendition)" ;;
    C) phase_title="Phase C — Multi-output (NVENC, 1 ffmpeg/stream)" ;;
    D) phase_title="Phase D — Failover & resilience" ;;
    E) phase_title="Phase E — DVR I/O" ;;
    F) phase_title="Phase F — CPU encoder fallback (libx264)" ;;
    H) phase_title="Phase H — Multi-protocol (HLS + DASH)" ;;
  esac

  echo
  echo "### $phase_title"
  echo

  if [[ "$phase" == "D" ]]; then
    cat <<EOF
| Case | Description | Measure | Result | Verdict |
| --- | --- | --- | --- | --- |
EOF
  else
    cat <<EOF
| Run | N | Ladder | CPU% | RAM (MB) | RAM% | GPU% | Enc% | Dec% | VRAM (MB) | Restart | Verdict |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
EOF
  fi

  for r in "${runs_in_phase[@]}"; do
    sum_file="$RESULTS/$r/summary.md"
    if [[ -f "$sum_file" ]]; then
      row=$(extract_row "$sum_file")
      if [[ -n "$row" ]]; then
        echo "$row"
      elif [[ "$phase" == "D" ]]; then
        echo "| $r | - | - | - | <missing> |"
      else
        echo "| $r | - | - | - | - | - | - | - | - | - | - | <missing> |"
      fi
    elif [[ "$phase" == "D" ]]; then
      echo "| $r | - | - | - | <no summary> |"
    else
      echo "| $r | - | - | - | - | - | - | - | - | - | - | <no summary> |"
    fi
  done

  echo
  echo "**Observations / ceiling for Phase $phase:** <TODO>"
done

cat <<EOF

---

## 5. Highlights & Bottlenecks

- **Practical ceilings observed:** <TODO>
- **First bottleneck hit:** <TODO>
- **Surprises / notable observations:** <TODO>

---

## 6. Issues, Saturation & Failures

Verdict legend:

- **PASS** — bench ran cleanly, every metric within thresholds
- **SATURATED** — bench ran cleanly but the system hit a resource ceiling (CPU p95 > 90%, stream(s) ended Degraded, transcoder restarts). This is the EXPECTED outcome of capacity testing.
- **FAIL** — real bench infrastructure / behavior failure. The sweep aborts on the first FAIL.

| Verdict | Severity | Phase / Run | Description | Per-run summary | Issue filed? |
| --- | --- | --- | --- | --- | --- |
EOF

# Auto-emit any non-PASS runs. SATURATED rows are EXPECTED for capacity tests
# (the whole point is finding the ceiling) — they appear here for visibility
# but should generally not need an issue filed.
# FAIL rows indicate a real bench-infrastructure or behavior failure.
for r in "${RUNS_FOUND[@]}"; do
  sum=$RESULTS/$r/summary.md
  [[ ! -f "$sum" ]] && continue
  verdict="" reason=""

  if grep -q '^\*\*FAIL\*\*' "$sum" 2>/dev/null; then
    verdict="FAIL"
    reason=$(grep '^\*\*FAIL\*\*' "$sum" | head -1 | sed 's/^\*\*FAIL\*\* — //; s/;$//')
  elif grep -q '^\*\*SATURATED\*\*' "$sum" 2>/dev/null; then
    verdict="SATURATED"
    reason=$(grep '^\*\*SATURATED\*\*' "$sum" | head -1 | sed 's/^\*\*SATURATED\*\* — //; s/;$//')
  elif grep -qE '\| Verdict \| \*\*FAIL\*\* \|' "$sum" 2>/dev/null; then
    verdict="FAIL"
    reason=$(grep -E '\| Result \| \*\*' "$sum" | head -1 \
      | sed -E 's/.*\| \*\*([^*]+)\*\* \|.*/\1/')
    [[ -z "$reason" ]] && reason="(see runs/$r.md)"
  fi

  [[ -n "$verdict" ]] && \
    echo "| $verdict | <TODO> | $r | $reason | [runs/$r.md](runs/$r.md) | <TODO> |"
done

cat <<EOF

---

## 7. Recommendations

### 7.1 For production deployments on similar hardware

- Sizing: <TODO>
- multi_output: <TODO>
- Profile / preset: <TODO>
- DVR config: <TODO>

### 7.2 For the codebase

- <TODO>

---

## 8. Attachments

Per-run digests are committed under \`runs/\`. Raw artifacts live on the
benchmarking host only.

| Run | Committed summary | Raw artifacts (host-local) |
| --- | --- | --- |
EOF
for r in "${RUNS_FOUND[@]}"; do
  echo "| \`$r\` | [runs/$r.md](runs/$r.md) | \`bench/results/$r/\` |"
done

cat <<EOF

Sweep-level: [sysinfo.txt](sysinfo.txt), [run-all.log](run-all.log).

---

## 9. Sign-off

| Reviewer | Date | Verdict |
| --- | --- | --- |
| <TODO> | <TODO> | <APPROVE / NEEDS-RERUN / BLOCK> |
EOF

} >"$OUT"

echo
echo "[aggregate] master report → $OUT"
echo "[aggregate] $(ls "$SWEEP_REPORTS/runs" | wc -l | tr -d ' ') per-run summaries copied to $SWEEP_REPORTS/runs/"
echo "[aggregate] $(grep -c '<TODO>' "$OUT") <TODO> markers remain for human fill-in."
echo
echo "Commit:"
echo "  git add bench/reports/$SWEEP/"
echo "  git commit -m 'bench: $SWEEP results'"
