#!/usr/bin/env bash
# Phase D — failover & resilience scenarios, fully scripted.
#
# Subcommands:
#   d1   2 inputs, kill primary publisher, measure switch latency
#   d2   1 transcoding stream, kill -9 the ffmpeg child, measure restart
#   d3   hot-add a push destination, verify HLS viewer sees no discontinuity
#   d4   push to a dead sink, verify pushes[] enters Reconnecting then Failed
#   all  run d1..d4 in sequence (with cleanup between)
#
# Usage:
#   bench/scripts/run-failover.sh d1
#   bench/scripts/run-failover.sh all
#
# Output (per case): bench/results/<id>/
#   timeline.txt          chronological event log (epoch ms · note)
#   runtime-pre.json      GET /api/v1/runtime before the disturbance
#   runtime-post.json     GET /api/v1/runtime after the disturbance
#   summary.md            auto-filled, with the row aggregate.sh consumes
#
set -euo pipefail

BENCH_ROOT=$(cd "$(dirname "$0")"/.. && pwd)
SCRIPTS=$BENCH_ROOT/scripts
API=${API:-http://127.0.0.1:8080}
RTMP_LISTEN=${RTMP_LISTEN:-rtmp://0.0.0.0:1935/live}
RTMP_LOCAL=${RTMP_LOCAL:-rtmp://127.0.0.1:1935/live}
HLS_BASE=${HLS_BASE:-http://127.0.0.1:8080}
INPUT=${INPUT:-$BENCH_ROOT/assets/sample-1080p.ts}
WARMUP=${WARMUP:-20}
DEAD_SINK=${DEAD_SINK:-rtmp://127.0.0.1:9999/dead}

ms() { date +%s%3N; }
note() { echo "$(ms) $*" >>"$TIMELINE"; echo "[d] $*"; }

api_check() {
  curl -fs --max-time 5 "$API/streams" >/dev/null \
    || { echo "[d] open-streamer not reachable at $API"; exit 1; }
}

create_stream() {
  local body=$1
  local code=$2
  local http
  http=$(curl -s -o /tmp/d.out -w "%{http_code}" \
    -XPOST "$API/streams/$code" -H 'Content-Type: application/json' -d "$body")
  [[ "$http" =~ ^20[01]$ ]] || { echo "create $code → save HTTP $http"; cat /tmp/d.out; return 1; }
  # POST /streams/<code> only persists; pipeline starts on /restart.
  http=$(curl -s -o /tmp/d.out -w "%{http_code}" -XPOST "$API/streams/$code/restart")
  [[ "$http" =~ ^20[04]$ ]] || { echo "restart $code → HTTP $http"; cat /tmp/d.out; return 1; }
  # Wait until the pipeline has flipped out of "stopped" so push slots are
  # registered before the publisher tries to connect.
  local deadline=$(( $(date +%s) + 10 ))
  while [[ $(date +%s) -lt $deadline ]]; do
    local status
    status=$(curl -fs "$API/streams/$code" 2>/dev/null \
      | grep -oE '"status"[[:space:]]*:[[:space:]]*"[^"]*"' | head -1 \
      | sed 's/.*"\([^"]*\)"$/\1/' 2>/dev/null || true)
    [[ -n "$status" && "$status" != "stopped" ]] && return 0
    sleep 0.2
  done
  echo "[d] $code: register timeout"
  return 1
}

delete_stream() {
  curl -s -XDELETE "$API/streams/$1" >/dev/null || true
}

push_source() {
  # spawn one RTMP publisher; echo PID
  local key=$1
  local logfile=$2
  ffmpeg -hide_banner -loglevel error -nostdin \
    -re -stream_loop -1 -i "$INPUT" \
    -c copy -f flv "$RTMP_LOCAL/$key" \
    </dev/null >"$logfile" 2>&1 &
  echo $!
}

# Extract first scalar value of a key from a JSON blob using jq if present,
# otherwise fall back to a tolerant grep. Used only for shallow lookups.
jget() {
  local file=$1 path=$2 default=${3:-}
  if command -v jq >/dev/null; then
    jq -r "$path // empty" "$file" 2>/dev/null || echo "$default"
  else
    # naive fallback for paths like .streams.d1.switches | length — not handled
    echo "$default"
  fi
}

# Count switches[] entries for stream $1 from /streams JSON response $2.
# /streams returns {"data": [{...stream..., "runtime": {"switches": [...]}}, ...]}
switches_count() {
  local code=$1 file=$2
  if command -v jq >/dev/null; then
    jq -r --arg c "$code" '(.data[]? | select(.code == $c) | .runtime.switches // []) | length' "$file" 2>/dev/null \
      || echo 0
  else
    grep -oE '"switches"[[:space:]]*:[[:space:]]*\[[^]]*\]' "$file" \
      | head -1 | grep -oE '"at"' | wc -l | tr -d ' '
  fi
}

# Increment of /metrics counter $1 between two metrics dumps $2 (before) $3 (after)
metric_delta() {
  local key=$1 before=$2 after=$3
  local b a
  b=$(awk -v k="^$key " '$0 ~ k {print $2; exit}' "$before" 2>/dev/null || echo 0)
  a=$(awk -v k="^$key " '$0 ~ k {print $2; exit}' "$after" 2>/dev/null || echo 0)
  awk -v a="${a:-0}" -v b="${b:-0}" 'BEGIN{printf "%d", a-b}'
}

# Write a Phase D summary row in the format aggregate.sh consumes
emit_summary() {
  local run_id=$1 desc=$2 measure=$3 result=$4 verdict=$5
  cat >"$DIR/summary.md" <<EOF
# Run Summary — $run_id (Phase D)

Auto-generated by \`run-failover.sh $(echo "$run_id" | tr 'A-Z' 'a-z')\` on $(date -Iseconds 2>/dev/null || date).

## Result

| Field | Value |
| --- | --- |
| Case | $run_id |
| Description | $desc |
| Measure | $measure |
| Result | **$result** |
| Verdict | **$verdict** |

## Timeline

\`\`\`text
$(cat "$TIMELINE")
\`\`\`

## Row to paste into the master report

\`\`\`markdown
| $run_id | $desc | $measure | $result | $verdict |
\`\`\`

## Files

\`\`\`
$(ls -la "$DIR" 2>/dev/null | tail -n +2)
\`\`\`
EOF
}

setup_dir() {
  RUN_ID=$1
  DIR=$BENCH_ROOT/results/$RUN_ID
  rm -rf "$DIR"
  mkdir -p "$DIR"
  TIMELINE=$DIR/timeline.txt
  : >"$TIMELINE"
  # Pre-emit a fallback FAIL summary so aggregate.sh always sees this case
  # even if the case function returns early (create_stream / push timeout).
  # The case body overwrites this with the real result on a normal completion.
  emit_summary "$RUN_ID" "(case did not complete)" "—" "did not run" "FAIL"
}

# ============================================================================
# D1 — failover on input failure
# ============================================================================
case_d1() {
  setup_dir D1
  local code=d1stream
  note "D1 begin: 2 inputs (push), kill primary"
  api_check

  delete_stream "$code"
  create_stream '{
    "code": "'$code'",
    "name": "d1 failover",
    "stream_key": "'$code'",
    "inputs": [
      {"url": "'"$RTMP_LISTEN/$code"'_pri", "priority": 0,
       "net": {"reconnect": true, "read_timeout_sec": 5}},
      {"url": "'"$RTMP_LISTEN/$code"'_bak", "priority": 1,
       "net": {"reconnect": true, "read_timeout_sec": 5}}
    ],
    "protocols": {"hls": true}
  }' "$code" || { echo "[d1] create failed"; return 1; }

  note "spawn primary publisher"
  PRIMARY_PID=$(push_source "${code}_pri" "$DIR/src-primary.log")
  note "spawn backup publisher"
  BACKUP_PID=$(push_source "${code}_bak" "$DIR/src-backup.log")

  trap 'kill $PRIMARY_PID $BACKUP_PID 2>/dev/null || true; delete_stream '"$code"'' RETURN

  note "warm-up ${WARMUP}s"
  sleep "$WARMUP"

  curl -fs "$API/streams" >"$DIR/runtime-pre.json"
  local before
  before=$(switches_count "$code" "$DIR/runtime-pre.json")
  note "switches_count before kill = $before"

  local kill_ts
  kill_ts=$(ms)
  note "killing primary publisher (pid=$PRIMARY_PID) at $kill_ts"
  kill -9 "$PRIMARY_PID" 2>/dev/null || true

  local switch_ts="" latency_ms=-1
  for i in $(seq 1 200); do
    sleep 0.1
    curl -fs "$API/streams" >"$DIR/runtime-poll.json" || continue
    local now
    now=$(switches_count "$code" "$DIR/runtime-poll.json")
    if [[ "$now" -gt "$before" ]]; then
      switch_ts=$(ms)
      latency_ms=$((switch_ts - kill_ts))
      note "switch detected after $((i*100))ms poll  · latency=${latency_ms}ms"
      break
    fi
  done

  cp "$DIR/runtime-poll.json" "$DIR/runtime-post.json" 2>/dev/null \
    || curl -fs "$API/streams" >"$DIR/runtime-post.json"

  local verdict="PASS"
  [[ "$latency_ms" -lt 0 ]] && verdict="FAIL"
  [[ "$latency_ms" -gt 5000 ]] && verdict="FAIL"

  kill "$BACKUP_PID" 2>/dev/null || true
  delete_stream "$code"
  trap - RETURN

  emit_summary D1 "2 inputs, kill primary" "switch latency (ms)" "${latency_ms} ms" "$verdict"
  note "D1 done: $verdict"
}

# ============================================================================
# D2 — transcoder ffmpeg crash + auto-restart
# ============================================================================
case_d2() {
  setup_dir D2
  local code=d2stream
  note "D2 begin: kill -9 transcoder ffmpeg, measure restart"
  api_check

  delete_stream "$code"
  # Use existing ABR legacy payload but rename the code
  local payload
  payload=$(sed "s/{{CODE}}/$code/g" "$BENCH_ROOT/payloads/abr3-legacy.json")
  create_stream "$payload" "$code" || { echo "[d2] create failed"; return 1; }

  note "spawn publisher"
  SRC_PID=$(push_source "$code" "$DIR/src.log")
  trap 'kill $SRC_PID 2>/dev/null || true; delete_stream '"$code"'' RETURN

  note "warm-up ${WARMUP}s"
  sleep "$WARMUP"

  curl -fs "$API/streams" >"$DIR/runtime-pre.json"
  curl -fs "$API/metrics" >"$DIR/metrics-pre.txt" 2>/dev/null || true

  local pids
  pids=$(pgrep -f "ffmpeg.*$code" | tr '\n' ' ')
  [[ -z "$pids" ]] && { echo "[d2] no ffmpeg pid for $code"; return 1; }
  note "transcoder ffmpeg pids: $pids"

  local kill_ts
  kill_ts=$(ms)
  note "killing all ffmpeg children at $kill_ts"
  # shellcheck disable=SC2086
  kill -9 $pids 2>/dev/null || true

  local restart_ts="" detect_ms=-1
  for i in $(seq 1 100); do
    sleep 0.1
    local newpids
    newpids=$(pgrep -f "ffmpeg.*$code" | tr '\n' ' ')
    # at least one new pid not in the original set
    for p in $newpids; do
      if ! grep -qw "$p" <<<"$pids"; then
        restart_ts=$(ms)
        detect_ms=$((restart_ts - kill_ts))
        note "ffmpeg restarted (new pid=$p) detect=${detect_ms}ms"
        break 2
      fi
    done
  done

  curl -fs "$API/streams" >"$DIR/runtime-post.json"
  curl -fs "$API/metrics" >"$DIR/metrics-post.txt" 2>/dev/null || true

  local restarts
  restarts=$(metric_delta "transcoder_restarts_total" "$DIR/metrics-pre.txt" "$DIR/metrics-post.txt")
  note "transcoder_restarts_total delta = $restarts"

  local verdict="PASS"
  [[ "$detect_ms" -lt 0 ]] && verdict="FAIL"
  [[ "$restarts" -lt 1 ]] && verdict="FAIL"

  kill "$SRC_PID" 2>/dev/null || true
  delete_stream "$code"
  trap - RETURN

  emit_summary D2 "kill -9 transcoder ffmpeg" "ffmpeg restart latency (ms) / restarts metric delta" \
    "${detect_ms} ms · restarts=${restarts}" "$verdict"
  note "D2 done: $verdict"
}

# ============================================================================
# D3 — hot-add push destination, HLS continuity unaffected
# ============================================================================
case_d3() {
  setup_dir D3
  local code=d3stream
  note "D3 begin: hot-add push, expect no HLS discontinuity"
  api_check

  delete_stream "$code"
  create_stream '{
    "code": "'$code'",
    "name": "d3 hot-add",
    "stream_key": "'$code'",
    "inputs": [{"url": "'"$RTMP_LISTEN/$code"'", "priority": 0,
                "net": {"reconnect": true, "read_timeout_sec": 5}}],
    "protocols": {"hls": true},
    "push": []
  }' "$code" || { echo "[d3] create failed"; return 1; }

  note "spawn publisher"
  SRC_PID=$(push_source "$code" "$DIR/src.log")
  trap 'kill $SRC_PID 2>/dev/null || true; delete_stream '"$code"'' RETURN

  note "warm-up ${WARMUP}s"
  sleep "$WARMUP"

  local hls_url=$HLS_BASE/$code/index.m3u8
  curl -fs "$hls_url" >"$DIR/playlist-pre.m3u8" || true
  local pre_disc
  pre_disc=$(grep -c '^#EXT-X-DISCONTINUITY' "$DIR/playlist-pre.m3u8" 2>/dev/null || echo 0)
  note "HLS discontinuities before = $pre_disc"

  note "PUT add push destination"
  local body
  body='{
    "code": "'$code'",
    "stream_key": "'$code'",
    "inputs": [{"url": "'"$RTMP_LISTEN/$code"'", "priority": 0}],
    "protocols": {"hls": true},
    "push": [{"url": "'"$DEAD_SINK/$code"'", "limit": 0}]
  }'
  local http
  http=$(curl -s -o /tmp/d3.out -w "%{http_code}" \
    -XPUT "$API/streams/$code" -H 'Content-Type: application/json' -d "$body")
  note "PUT → HTTP $http"

  note "observe 30s"
  sleep 30

  curl -fs "$hls_url" >"$DIR/playlist-post.m3u8" || true
  local post_disc
  post_disc=$(grep -c '^#EXT-X-DISCONTINUITY' "$DIR/playlist-post.m3u8" 2>/dev/null || echo 0)
  note "HLS discontinuities after  = $post_disc"

  local added=$((post_disc - pre_disc))
  local verdict="PASS"
  [[ "$added" -gt 0 ]] && verdict="FAIL"

  curl -fs "$API/streams" >"$DIR/runtime-post.json"

  kill "$SRC_PID" 2>/dev/null || true
  delete_stream "$code"
  trap - RETURN

  emit_summary D3 "hot-add push destination" "HLS discontinuities introduced" \
    "${added} new" "$verdict"
  note "D3 done: $verdict"
}

# ============================================================================
# D4 — push to dead sink, observe state machine
# ============================================================================
case_d4() {
  setup_dir D4
  local code=d4stream
  note "D4 begin: push to dead sink, observe state machine"
  api_check

  delete_stream "$code"
  create_stream '{
    "code": "'$code'",
    "name": "d4 dead push",
    "stream_key": "'$code'",
    "inputs": [{"url": "'"$RTMP_LISTEN/$code"'", "priority": 0,
                "net": {"reconnect": true, "read_timeout_sec": 5}}],
    "protocols": {"hls": true},
    "push": [{"url": "'"$DEAD_SINK/$code"'", "limit": 5,
              "retry_timeout_sec": 2}]
  }' "$code" || { echo "[d4] create failed"; return 1; }

  note "spawn publisher"
  SRC_PID=$(push_source "$code" "$DIR/src.log")
  trap 'kill $SRC_PID 2>/dev/null || true; delete_stream '"$code"'' RETURN

  note "poll pushes[] state for 30s"
  local seen_starting=0 seen_reconnecting=0 max_attempts=0 final_state=""
  for i in $(seq 1 30); do
    sleep 1
    curl -fs "$API/streams" >"$DIR/runtime-poll.json" || continue
    local state attempts
    if command -v jq >/dev/null; then
      state=$(jq -r --arg c "$code" '.data[]? | select(.code == $c) | .runtime.publisher.pushes[0].status // ""' "$DIR/runtime-poll.json")
      attempts=$(jq -r --arg c "$code" '.data[]? | select(.code == $c) | .runtime.publisher.pushes[0].attempt // 0' "$DIR/runtime-poll.json")
    else
      state=$(grep -oE '"status"[[:space:]]*:[[:space:]]*"[^"]+"' "$DIR/runtime-poll.json" | tail -1 | sed 's/.*"\([^"]*\)"$/\1/')
      attempts=$(grep -oE '"attempt"[[:space:]]*:[[:space:]]*[0-9]+' "$DIR/runtime-poll.json" | tail -1 | grep -oE '[0-9]+$' || echo 0)
    fi
    [[ -n "$state" ]] && note "t=${i}s state=$state attempts=$attempts"
    [[ "$state" == "starting" ]] && seen_starting=1
    [[ "$state" == "reconnecting" ]] && seen_reconnecting=1
    [[ -n "$attempts" && "$attempts" -gt "$max_attempts" ]] && max_attempts=$attempts
    final_state=$state
  done

  cp "$DIR/runtime-poll.json" "$DIR/runtime-post.json" 2>/dev/null || true

  local verdict="PASS"
  # Expectation: enters Starting → Reconnecting (or Failed) and attempts > 1
  [[ "$max_attempts" -lt 2 ]] && verdict="FAIL"
  [[ "$seen_reconnecting" -eq 0 && "$final_state" != "failed" ]] && verdict="FAIL"

  kill "$SRC_PID" 2>/dev/null || true
  delete_stream "$code"
  trap - RETURN

  emit_summary D4 "push to dead sink" "state machine cycles + attempts" \
    "final=${final_state} · attempts=${max_attempts}" "$verdict"
  note "D4 done: $verdict"
}

# ============================================================================
case ${1:-} in
  d1)  case_d1 ;;
  d2)  case_d2 ;;
  d3)  case_d3 ;;
  d4)  case_d4 ;;
  all) case_d1; case_d2; case_d3; case_d4 ;;
  *)
    echo "Usage: $0 {d1|d2|d3|d4|all}"
    exit 1
    ;;
esac
